dell/csm-replication

api/v1alpha1/dellcsireplicationgroup_types.go
repctl/README.md
repctl/cmd/repctl/main.go
repctl/pkg/cmd/cluster.go
repctl/pkg/cmd/failback.go
repctl/pkg/cmd/failover.go
repctl/pkg/cmd/list.go
repctl/pkg/cmd/reprotect.go
repctl/pkg/cmd/swap.go
repctl/pkg/k8s/cluster.go
scripts/uninstall.sh

- Implemented --wait flag in repctl
- Re-imagined overall repctls look&feel
- Re-worked repctl actions CLI
- Added uninstall script, that can handle both helm and plain-manifests
https://github.com/dell/csm/issues/70
https://github.com/dell/csm/issues/66
| |
- [1/2] I have made corresponding changes to the documentation
Manually tested in 2-cluster replication environment

Repctl ux improvements & uninstall script

---

cmd/csi-replicator/main.go

A few sentences describing the overall goals of the pull request's commits.
| |

change metric's port

---

repctl/pkg/k8s/cluster.go

Disallow upgrading CRDs via simple k8s update because this can cause unexpected behavior with existing Custom Resources
| https://github.com/dell/csm/issues/66 |

Disallow upgrading CRDs via simple k8s update

---

config/manager/manager.yaml
deploy/controller.yaml
helm/csm-replication/values.yaml

Updated controller image in kustomize, generated manifest and helm values
| https://github.com/dell/csm/issues/69 |

Updated controller image

---

cmd/csi-replicator/main.go
cmd/replication-controller/main.go
pkg/config/config.go

publish event when  controller is back to normal after config changes

publish event when  back to normal

---

repctl/examples/powerscale_example_values.yaml
repctl/pkg/cmd/create.go
repctl/pkg/cmd/templates/isilon_source.yaml
repctl/pkg/cmd/templates/isilon_target.yaml

Adds generation of sc for powerscale to repctl
| https://github.com/dell/csm/issues/128 |

Add generation of sc for powerscale to repctl

---

repctl/examples/powermax_example_values.yaml
repctl/examples/powerscale_example_values.yaml
repctl/examples/powerstore_example_values.yaml
repctl/pkg/cmd/create.go
repctl/pkg/cmd/templates/isilon_source.yaml
repctl/pkg/cmd/templates/isilon_target.yaml
repctl/pkg/cmd/templates/powermax_source.yaml
repctl/pkg/cmd/templates/powermax_target.yaml
repctl/pkg/cmd/templates/powerstore_source.yaml
repctl/pkg/cmd/templates/powerstore_target.yaml

Honor remoteRetentionPolicy in `repctl` storage classes
| https://github.com/dell/csm/issues/128 |

Honor remoteRetentionPolicy in repctl storage classes

---

config/manager/manager.yaml
deploy/controller.yaml
go.mod
go.sum
helm/csm-replication/Chart.yaml
helm/csm-replication/values.yaml
repctl/cmd/repctl/main.go
repctl/go.mod
repctl/go.sum

Prepared changes for release 1.2
| https://github.com/dell/csm/issues/128 |

Prepared changes for release 1.2

---

controllers/csi-migrator/persistentvolume_controller.go
repctl/go.mod

Migration Type Detection
https://github.com/dell/csm/issues/265
https://github.com/dell/csm/issues/267
Manually e2e

migration types detection added

---

Makefile
image.mk

Updates for Makefiles for migration sidecar.
https://github.com/dell/csm/issues/265
https://github.com/dell/csm/issues/267
Manually

Makefiles updates

---

.github/CODEOWNERS
controllers/csi-migrator/persistentvolume_controller.go

Fixed migrator bug and updated CODEOWNERS
| https://github.com/dell/csm/issues/266 | 
- [] I have maintained at least 90% code coverage
manually 2e2

updated codeowners, fixed migrator error

---

.github/workflows/actions.yml

A few sentences describing the overall goals of the pull request's commits.
|https://github.com/dell/csm/issues/243 |

github actions fix

---

controllers/csi-replicator/monitoring.go
go.mod
go.sum
repctl/go.mod
repctl/go.sum

Update RGs status to EMPTY if no PVs were found
Should be changed to use correct commit id after https://github.com/dell/dell-csi-extensions/pull/18 is merged 
| https://github.com/dell/csm/issues/286 |

Update RGs status to EMPTY if no PVs were found

---

controllers/csi-replicator/persistentvolume_controller.go
controllers/replication-controller/dellcsireplicationgroup_controller.go

Case insensitive checks, proper logging in RG reconcile
| https://github.com/dell/csm/issues/307 |

Case insensitive checks, proper logging in RG reconcile

---

controllers/common.go
controllers/constants.go
controllers/csi-migrator/persistentvolume_controller.go
controllers/csi-migrator/persistentvolume_controller_test.go
go.mod
go.sum
pkg/csi-clients/migration/migration.go
pkg/csi-clients/migration/migration_fake.go

Added migration NS
[List the GitHub issues impacted by this PR:
GitHub Issue # [265](https://github.com/dell/csm/issues/265)
manually e2e

Migration namespace

---

controllers/csi-migrator/persistentvolume_controller.go

|https://github.com/dell/csm/issues/332 |

migration bug fix missing annotation

---

repctl/pkg/cmd/failover.go

Typo in the logs

---

config/manager/manager.yaml
deploy/controller.yaml
helm/csm-replication/Chart.yaml
helm/csm-replication/values.yaml
repctl/cmd/repctl/main.go

Updated the replication controller module version to release 1.4.
No changes to replicator and migrator sidecars.
| https://github.com/dell/csm/issues/491 |

Update the version to 1.4

---

.github/containerscan/allowedlist.yaml
.github/workflows/actions.yml

- Removed fixed CVE from allowedList.
- Updated GoSec to 2.15.
- Added new images for GitHub container scan.
| https://github.com/dell/csm/issues/583 |
All PR checks passed.

GitHub workflow action updates

---

controllers/csi-node-rescanner/dellcsimigrationgroup_controller.go

A few sentences describing the overall goals of the pull request's commits.
- Updates Pod filter for removing rescan label
| https://github.com/dell/csm/issues/696|
- Cluster Test

Updates Pod filter for removing rescan label

---

Dockerfiles/Dockerfile.init

Fix build of init image. Due to changes in new packages and their dependencies.
| https://github.com/dell/csm/issues/758|

Fix init image build

---

Dockerfiles/Dockerfile
Dockerfiles/Dockerfile.init
image.mk

Update ubi micro image
| [790](https://github.com/dell/csm/issues/790)|
Manual testing done

Update ubi micro image

---

core/semver/semver.go
repctl/pkg/cmd/cluster.go
repctl/pkg/cmd/edit.go
repctl/pkg/k8s/cluster.go
repctl/pkg/k8s/cluster_test.go
test/mock-server/server/server.go
test/mock-server/stub/storage.go
test/mock-server/stub/stub.go
test/mock-server/stub/stub_test.go

Removed deprecated ioutil package.
| https://github.com/dell/csm/issues/916 |

Removed deprecated ioutil package

---

go.mod
go.sum

Update dell-csi-extensions to the latest
| https://github.com/dell/csm/issues/1012 |

Update dell-csi-extensions to the latest

---

.github/workflows/actions.yml
.github/workflows/linters.yaml
go.mod
go.sum
repctl/go.mod
repctl/pkg/cmd/create.go
repctl/pkg/cmd/migrate.go

Update go version to 1.22

---

Dockerfiles/Dockerfile
licenses/LICENSE

Adding license to the image and folder in repo to fix Preflight Checks failures.
| |

Adding license to fix Preflight Checks failures

---

config/manager/manager.yaml
deploy/controller.yaml
scripts/install.sh

update controller image to 1.8.1 for patch 1.10.2 release. 
|https://github.com/dell/csm/issues/1280 |
- [] I have performed a self-review of my own code to ensure there are no formatting, vetting, linting, or security issues

update controller image

---

.github/workflows/actions.yml
Makefile
image.mk
scripts/build-ubi-micro.sh

This PR updates the UBI micro dependencies.
| https://github.com/dell/csm/issues/1221 |

Updating ubi micro dependencies

---

config/manager/manager.yaml
deploy/controller.yaml
repctl/cmd/repctl/main.go
repctl/go.mod
scripts/install.sh

Updated latest versions in the script and other places.
| https://github.com/dell/csm/issues/1221 |

Updated script versions for CSM 1.11

---

repctl/examples/powerstore_example_values.yaml
repctl/pkg/cmd/create.go
repctl/pkg/cmd/create_test.go
repctl/pkg/cmd/templates/powerstore_source.yaml
repctl/pkg/cmd/templates/powerstore_target.yaml

repctl to support new storage class replication SYNC and ASYNC mode
| https://github.com/dell/csm/issues/1443 |
Create storage class with SYNC changes :
Set mode as ASYNC and rpo as five minutes:
Set mode as SYNC :

repctl to support new storage class replication SYNC and ASYNC mode

---

config/rbac/role.yaml
config/sidecar-rbac/role.yaml
deploy/controller.yaml
deploy/role.yaml

This PR update RBAC rules for PowerMax Replication.
| https://github.com/dell/csm/issues/1751 |
Logs: [pmax-replication-e2e-repctl.txt](https://github.com/user-attachments/files/20067031/pmax-replication-e2e-repctl.txt)

Update RBAC rules for PowerMax Replication

---

Dockerfiles/Dockerfile
config/manager/manager.yaml
deploy/controller.yaml
repctl/cmd/repctl/main.go
repctl/cmd/repctl/main_test.go
scripts/install.sh

Version Bump for CSM 1.15
| https://github.com/dell/csm/issues/1896|

Version Bump for CSM 1.15
