dell/csm-replication

Dockerfiles/Dockerfile, Dockerfiles/Dockerfile.dev
Updated ubi-min image version to newer used by drivers
(in PRs  https://github.com/dell/csi-powerscale/pull/30 and https://github.com/dell/csi-powermax/pull/33 for example)
| https://github.com/dell/csm/issues/102 |
=> Updated ubi-min image version to newer used by drivers

helm/csm-replication/templates/controller.yaml, helm/csm-replication/values.yaml
Adds support for closed OS networks by enabling ability to specify .spec.hostAliases during installation
Manually in real env
=> Added hostAliases to helm's values

README.md, repctl/examples/powerscale_example_values.yaml, repctl/pkg/cmd/templates/isilon_source.yaml, repctl/pkg/cmd/templates/isilon_target.yaml
Use correct value as `remoteSystem` parameter
| https://github.com/dell/csm/issues/116 |
=> Use correct value as remoteSystem parameter

repctl/examples/powerscale_example_values.yaml, repctl/pkg/cmd/create.go, repctl/pkg/cmd/templates/isilon_source.yaml, repctl/pkg/cmd/templates/isilon_target.yaml
Repctl tool update to support new storage class parameters for PowerScale replication. Please note that the changes are only in the repctl and does not affect replication module code.
PowerScale driver changes and documentation update are handled in their repos.
| https://github.com/dell/csm/issues/514 |
- Ran repctl tool to create storage classes on both source and target k8s clusters with different combination of newly added parameters.
- AzServiceIp is optional, so its generation is handled accordingly.
- Provisioning of PVs using the newly generated storage class is successful.
=> Repctl tool update to support new storage class parameters for PowerScale replication

helm/csm-replication/templates/controller.yaml, repctl/pkg/cmd/cluster.go
Instead of using the `default` service account and trying to patch it to contain the correct secret, we create a new service account for the `dell-replication-controller` and use that throughout. This limits the pre-hook generation as modifying a new service account through helm is simple.
| https://github.com/dell/csm/issues/463 |
- Ensured that when installing the dell-replication-controller, the new service account contained the generated token and mountable secret.
- Ensured that running `repctl inject cluster --use-sa` no longer fails and properly creates the secrets on both …
=> Add new service account to be used

controllers/csi-replicator/monitoring.go, repctl/pkg/cmd/failback.go
When RG status gets updated (as part of regular monitoring) when an action is in progress, the action result update fails. Due to that, the action gets executed again. So RG status polling is skipped when an action is being executed and the action anyways update the RG status at the end.
| https://github.com/dell/csm/issues/558 |
| https://github.com/dell/csm/issues/532 |
Tested all PowerScale replication actions and no issues are detected. Monitored the log w.r.t action and RG status poll.
[RG status poll log times.txt](https://github.com/dell/csm-replication/files/10230095/RG.status.poll.log.times.txt)
=> Skip RG status poll/update if any action is being executed

repctl/examples/powerflex_example_values.yaml, repctl/pkg/cmd/create.go, repctl/pkg/cmd/templates/vxflexos_source.yaml, repctl/pkg/cmd/templates/vxflexos_target.yaml
Adds support of `PowerFlex` to `repctl`. This will allow the creation of storage classes with the appropriate template using `repctl` for PowerFlex.
| https://github.com/dell/csm/issues/618 |
=> Add pflex support

controllers/replication-controller/dellcsireplicationgroup_controller.go, deploy/controller.yaml, helm/csm-replication/templates/controller.yaml, pkg/connection/interface.go, pkg/connection/k8sconnections.go, repctl/pkg/cmd/snapshot.go
This is an enhancement to the snapshot action handling in the controller. As requested, this checks to see if the desired namespace exists, if it doesn't then it attempts to create it.
| https://github.com/dell/csm/issues/618 |
=> Add Namespace Creation on Snapshot Action

cmd/csi-replicator/main.go, controllers/constants.go, controllers/csi-replicator/dellcsireplicationgroup_controller.go, controllers/csi-replicator/persistentvolume_controller.go, controllers/replication-controller/dellcsireplicationgroup_controller.go
Retrieves the cluster UID of the system that is unique between clusters at the creation of the sidecar. The intention is to provide this information to the drivers if they wish to use it in any form when creating the name of the RCG for better identification.
It is ensured that the cluster UID is only retrieved once to avoid constantly querying during reconciles.
Example:
In PowerFlex, cluster UID is added to the name. It is truncated to fit the limitations of the max name length.
| https://github.com/dell/csm/issues/618 |
=> Retrieve Cluster UID

Dockerfiles/Dockerfile.init
Fixed new Trivy scan vulnerability reported in the init image.
Updated kubectl from v1.25.6 to v1.25.7 for golang.org/x/net update.
| https://github.com/dell/csm/issues/583 |
Performed sanity tests with the init image deployment and upgrade script (locally modified) to test different scenarios.
[init container log.txt](https://github.com/dell/csm-replication/files/10962012/init.container.log.txt)
=> Updated kubectl version for the init image

.github/containerscan/allowedlist.yaml, scripts/gen_kubeconfig.sh
Determine the existence of `kubectl` and `oc` commands. If the `oc` command is present, use that for extracting the service accounts and generating the kubeconfigs.
| https://github.com/dell/csm/issues/815 |
=> Add determination of valid command for kubeconfig generation

repctl/pkg/cmd/migrate.go
Repctl migrate cmd: Set migration namespace only when it is provided in the optional _target-ns_ parameter.
| https://github.com/dell/csm/issues/841 |
Ran ./repctl migrate cmd with and without _target-ns_ parameter and it worked. Thanks @boyamurthy for testing.
=> Repctl: Set migration namespace only when it is provided

Dockerfiles/Dockerfile.init
Updated kubectl version used in the init container image for fixing security vulnerabilities. Merging Code of release branch with main. Refer the pull request for more details https://github.com/dell/csm-replication/pull/101
| https://github.com/dell/csm/issues/743|
=> Updated kubectl to v1.26.6 (#101)

image.mk
Use common base image
| https://github.com/dell/csm/issues/1031 |
=> Use common base image

test/e2e-framework/utils/utils.go
Only initialize scheme once during unit tests to prevent a race condition.
| |
=> Only initialize scheme once during unit tests

scripts/install.sh
The 1.7.0 script point to an older version of the helm-chart.
This will have to bumped next time
| |
Tested at Boeing
=> Point to the correct release version `1.7.0`

repctl/Makefile
Otherwise it crashes on certain distro due to missing GLIBC dependencies
During a PoC we could not use the distributed `repctl` and had to rebuild it. Static libs are <3
| |
Built on my Fedora 40 tested on a RHEL 8.x
=> Build repctl with static lib

scripts/pvcremap.go
The goal of the script is to create a new PVC that remap local and remote PV in the case of failover/failback actions.
Currently, this is a standalone program, but will eventually be integrated into the replication controller.
| N/A |
=> Initial pvcremap script

scripts/pvcremap.go
Update the pvcremap.go to remap all the pvcs within the specified replication group.
Testing with commandline: 
`go build pvcremap.go`
`./pvcremap -rg <rg-id>`
|N/A |
=> Remap all the pvcs within the specified replication group

README.md
Root cause: `make build` under repctl fails due to missing the `glibc-devel-static` devel package.
Fix: Update a README section to address the issue. Additionally, the broken link in the Installation section is fixed.
|https://github.com/dell/csm/issues/1330 |
=> Update README instruction for repctl static build on openSUSE

repctl/Makefile
Revert [137](https://github.com/dell/csm-replication/pull/137) and add a separate target, build-static for building a static binary. 
| [1385](https://github.com/dell/csm/issues/1385)|
No additional tests added as no functionality was changed.
=> [csm-1385] Revert change to build static repctl.

repctl/cmd/repctl/main.go, repctl/go.mod, scripts/install.sh
csm-replication version updated to v1.10.0
| https://github.com/dell/csm/issues/1221 |
=> csm-replication version updated to v1.10.0

Makefile
GitHub actions was only running unit test for the controller directory and repctl.
This commit creates new makefile targets for the directories with relevant code for which unit tests should be run.
> Note: the `make test` target would have been used, but it also attempts to run the golang tests for e2e in the ./test directory.
| https://github.com/dell/csm/issues/1559 |
Used the Makefile target `make unit-test` to execute the unit tests.
=> Adding missing test dirs to unit-test target

Dockerfiles/Dockerfile
Added the required labels to the image container so that it can pass preflight checks.
| https://github.com/dell/csm/issues/1667 |
Built image. Docker inspect shows:
{
"architecture": "x86_64",
"build-date": "2024-08-27T19:24:54",
"com.redhat.component": "ubi9-micro-container",
"com.redhat.license_terms": "https://www.redhat.com/en/about/red-hat-end-user-license-agreements#UBI",
"description": "CSI Replication controller",
"distribution-scope": "public",
"io.buildah.version": "1.29.4",
"io.k8s.description": "Very small image which doesn't install the package manager.", …
=> Add preflight required labels.

cmd/replication-controller/main.go, cmd/replication-controller/main_test.go, controllers/replication-controller/dellcsireplicationgroup_controller.go, controllers/replication-controller/dellcsireplicationgroup_controller_test.go, pkg/connection/interface.go, pkg/connection/k8sconnections.go
- Contains changes for PVC remap feature changes rebased on top of the latest commits. Original changes are part of the PR 
https://github.com/dell/csm-replication/pull/147
- Increased the UT coverage 
| https://github.com/dell/csm/issues/1850|
-Tested the functionality for PowerFlex on single cluster - Deatiled Test screenshots are captured as part of ECS01C-90
-Tested the functionality for PowerScale on stretched cluster - TDeatiled est screenshots are captured as part of ECS01C-87
Before Failover:
After Failover:
=> PVC remap feature for csm-replication on stretched cluster

deploy/controller.yaml
Add `disable-pvc-remap` flag in argument to enable/disable pvcremap feature in replication controller
| https://github.com/dell/csm/issues/1850|
=> Add argument to enable/disable pvcremap feature in replication controller

cmd/replication-controller/main.go, cmd/replication-controller/main_test.go, controllers/replication-controller/persistentvolumeclaim_controller.go, deploy/controller.yaml
- Parameterize PVC creation on Target cluster
[ provided an option, to decide whether PVC can be provisioned on Target cluster or not, Instead can simply populate claimref on target PV ]
|https://github.com/dell/csm/issues/1862|
Argument added to the replication controller
=> Claimref feature params

repctl/examples/powerstore_example_values.yaml, repctl/pkg/cmd/create.go, repctl/pkg/cmd/create_test.go, repctl/pkg/cmd/templates/powerstore_source.yaml, repctl/pkg/cmd/templates/powerstore_target.yaml
Rename to SharedNFS for creating StorageClasses
| https://github.com/dell/csm/issues/1742 |
=> Rename to SharedNFS for creating StorageClasses

cmd/replication-controller/main.go, controllers/replication-controller/persistentvolume_controller.go, controllers/replication-controller/persistentvolumeclaim_controller.go, controllers/replication-controller/persistentvolumeclaim_controller_test.go
Whit this changes we are Generating the PVC in the target site, to reserve/bind the PV using the ClaimRef on replicated site.
Creation of the namespace if not already present on target site is also handled. 
|https://github.com/dell/csm/issues/1862 |
-
=> Claim ref feature

repctl/examples/powerstore_example_values.yaml, repctl/pkg/cmd/create.go, repctl/pkg/cmd/create_test.go, repctl/pkg/cmd/templates/powerstore_source.yaml, repctl/pkg/cmd/templates/powerstore_target.yaml
Remove reference to Shared NFS in Repctl.
| https://github.com/dell/csm/issues/1742 |
=> Remove Reference to Shared NFS

controllers/replication-controller/dellcsireplicationgroup_controller.go, controllers/replication-controller/dellcsireplicationgroup_controller_test.go
In a single or stretched cluster, when a failover occurs, we remap the Persistent Volume Claim (PVC) from the source Persistent Volume (PV) to the replicated PV. However, this process leaves the claimRef field on the source PV empty, allowing any user to potentially claim it. To prevent this, this Pull Request (PR) updates the claimRef field to reserved/reserved in these scenarios, effectively blocking the PV from being claimed by unauthorized users.
| https://github.com/dell/csm/issues/1924 |
Tested the Failover and reprotect workflow on single cluster for PowerFlex and the screenshots are as below:
Status of PV, PVC and RG before Failover
Status of PV, PVC and RG after Failover (original PV "claimRef" has …
=> Update local pv cliamref to reserved/reserved after fail over

controllers/csi-node-rescanner/dellcsimigrationgroup_controller.go, pkg/noderescan/noderescan.go, pkg/noderescan/noderescan_test.go
This PR refactors the `utils` package to `noderecan` to comply with our linter's 'unhelpful name' rule and improve code clarity.
| https://github.com/dell/csm/issues/1896 |
```
which: no controller-gen in (/root/.local/bin:/root/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/usr/local/go/bin)
which: no kustomize in (/root/.local/bin:/root/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/usr/local/go/bin)
(cd core; rm -f core_generated.go; go generate)
go run core/semver/semver.go -f mk > semver.mk
go fmt ./...
go vet ./...
go: creating new go.mod: module tmp
go: …
```
=> Refactor utils pkg 

.github/workflows/create-tag-release.yaml, .github/workflows/release-image.yaml
I've split the release workflow into two distinct parts:
1. Create Tag and Release
2. Release Image
This change was made to address an issue in the previous workflow where images were being released with incorrect semantic versioning. By separating the workflows, we now:
- First, create the release tag.
- Then, manually rebuild the nightly image to ensure it includes the correct semver version.
- Finally, trigger the Release Image workflow, which now reliably publishes images with the correct version.
| https://github.com/dell/csm/issues/1995
This is tested in forked repo, created the tag and release, pushed the images to test quay folder
=> Update Release Workflow

repctl/pkg/cmd/action.go, repctl/pkg/cmd/action_test.go, repctl/pkg/config/constants.go
This PR addresses gaps in karavi replication tests for powermax driver.
Powermax was missing an action for a replication group which would eventually fail the karavi tests.
Adding the "ESTABLISH" action for powermax helps in creating replication group.
|https://github.com/dell/csm/issues/2001 |
I had successfull sync and async replication run with powermax driver
=> Adding Powermax replication group action
